import type { Metadata } from "next";
import PhotoProvider from "@/provider/PhotoProvider";
import AntdProvider from "@/provider/AntdProvider";
import PhotoFileProvider from "@/provider/PhotoFileProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdProvider>
          <PhotoFileProvider>
            <PhotoProvider>{children}</PhotoProvider>
          </PhotoFileProvider>
        </AntdProvider>
      </body>
    </html>
  );
}
